# Generated by Django 3.2.3 on 2024-02-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0003_customuser_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrowing',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
