# Generated by Django 3.2.3 on 2024-02-07 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0005_borrowing_reason_for_borrowing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowing',
            name='email',
        ),
        migrations.RemoveField(
            model_name='borrowing',
            name='name',
        ),
    ]
